import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { CaseTypeProvider } from "@/providers/case-provider"
import { Backbround } from "@/components/backbround"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"
import "./globals.css"

const jet = JetBrains_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={cn(jet.className, "h-dvh overflow-hidden flex")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <CaseTypeProvider>
            <Backbround />
            <Toaster />
            {children}
          </CaseTypeProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
